### ISSUE TITLE
GridView inside SlidingUpPanel

### ISSUE THREAD

**Issue by bhuvneshvarma** [umano/AndroidSlidingUpPanel#427] opened 2015-04-07 19:00 UTC
I have implemented slidingUpPanel and I am facing with following issues-

1.My panel consists of gridview and if i add images to gridview then the sliding up and down of panel becomes tough.Many times i have to swipe 3-4 times to swipe up-down the panel.However if i am not adding images to gridview and panel is blank then slide is smooth.

2.Gridview items shows lot of space at top and bottom and also not all images are shown.

Below is my code-

xml
 

      <com.sothree.slidinguppanel.SlidingUpPanelLayout
            xmlns:sothree="http://schemas.android.com/apk/res-auto"
            android:id="@+id/sliding_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="bottom"
            sothree:umanoPanelHeight="300dp"
            sothree:umanoShadowHeight="4dp"
            android:visibility="visible">
    
        <RelativeLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/maps"
    
            android:visibility="visible">
            <fragment
                android:id="@+id/location_map"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                class="com.google.android.gms.maps.MapFragment" />
            <ImageView
                android:id="@+id/btn_video"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_marginLeft="5dp"
                android:src="@drawable/create_video_icon"
                android:layout_alignParentLeft="true" />
            <RelativeLayout
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:background="@color/search_bg_color"
                android:layout_marginRight="90dp"
                android:layout_toRightOf="@+id/btn_video"
                android:orientation="horizontal" >
    
    
                <ImageView
                    android:id="@+id/btn_find"
                    android:layout_width="40dp"
                    android:layout_height="40dp"
                    android:src="@drawable/search"
    
                    android:layout_alignParentRight="true" />
    
                <EditText
                    android:id="@+id/location"
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content"
                    android:inputType="text"
                    android:hint="@string/hnt_et_location"
    
                    android:layout_toLeftOf="@id/btn_find" />
    
            </RelativeLayout>
        </RelativeLayout>
            <RelativeLayout
                xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:id="@+id/panelslider"
                android:background="#000000"
                android:visibility="visible">
                <GridView
                    android:id="@+id/maps_video_gridview"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
    
    android:layout_alignParentTop="true"
                    android:divider="@color/white_clean"
                    android:verticalSpacing="10dp"
                    android:horizontalSpacing="10dp"
                    android:numColumns="2"
    
    
                    android:visibility="visible" />
            </RelativeLayout>
        </com.sothree.slidinguppanel.SlidingUpPanelLayout>
Code-
 

      slidingPaneLayout.setDragView(findViewById(R.id.panelslider));
            slidingPaneLayout.setEnableDragViewTouchEvents(true);
     mMclickedAdapter = new MclickedAdapter(getApplicationContext(), searchResponses);
                            mapsVideoGrid.setAdapter(mMclickedAdapter);

**Comment by tokudu** [comment] 2015-04-12 00:34
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/116

**Closed by tokudu** 2015-04-12 00:34 UTC
