### ISSUE TITLE
getLeft() bug

### ISSUE THREAD

**Issue by BeetLab** [umano/AndroidSlidingUpPanel#505] opened 2015-07-20 09:32 UTC
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.smoothSlideTo(SlidingUpPanelLayout.java:1202)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.smoothToBottom(SlidingUpPanelLayout.java:437)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.setPanelHeight(SlidingUpPanelLayout.java:430)
       at com.interstar.favnlove.BL_GridTwoRowsFragment.initWantHere(BL_GridTwoRowsFragment.java:362)
       at com.interstar.favnlove.BL_GridTwoRowsFragment.onCreateView(BL_GridTwoRowsFragment.java:139)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:953)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:456)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

after panel init. I love maven and modern libraries on-air updates, but it was very scary half-an-hour, when my app began to crash...)

**Comment by BeetLab** [comment] 2015-07-20 09:42
rolling back to 3.0.0 fixed issue

**Comment by Transformat** [comment] 2015-07-22 11:14
Got the same bug . Rolling back to 3.0.0 now

**Comment by tbsandee** [comment] 2015-07-24 22:42
I get this too. Hard to argue it's not a bug in the implementation of setPanelHeight().

You can work around it by making sure all calls to setPanelHeight() occur after the initial layout of the view. Something like this:

```java

    protected SlidingUpPanelLayout mSlidingPanel;

    protected void setSlidingPanelHeight(final int height) {
        mSlidingPanel.post(new Runnable() {
            @Override
            public void run() {
                if (mSlidingPanel != null) {
                    mSlidingPanel.setPanelHeight(height);
                }
            }
        });
    }
```

**Comment by tokudu** [comment] 2015-07-25 19:57
Fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/c9bc8791f24796e52c36c6b056b8d890c626a9c9

**Closed by tokudu** 2015-07-25 19:58 UTC
