### ISSUE TITLE
Spurious drag cancel when pulling panel down

### ISSUE THREAD

**Issue by pazustep** [umano/AndroidSlidingUpPanel#528] opened 2015-08-18 14:48 UTC
When pulling the panel down from the expanded state, I'm getting spurious drag cancellations shortly after starting the drag down, and sometimes when passing the anchor point.

Here's a screen recording of that happening: http://1drv.ms/1JeX0D6

The main view is a `MapView` from MapBox SDK; the second view is a `ScrollView`. Here'se the main layout file:

```
<com.sothree.slidinguppanel.SlidingUpPanelLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:id="@+id/item_location_sliding_panel"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:umanoPanelHeight="88dp"
    sothree:umanoShadowHeight="4dp"
    sothree:umanoAnchorPoint="0.5"
    sothree:umanoFadeColor="@android:color/transparent"
    sothree:umanoScrollableView="@+id/item_location_scroll">

    <com.mapbox.mapboxsdk.views.MapView
        android:id="@+id/item_location_mapview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <include layout="@layout/item_location_details"/>
</com.sothree.slidinguppanel.SlidingUpPanelLayout>
```

The included layout:

```
<ScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/item_location_scroll"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/light_gray">
...
</ScrollView>

**Comment by emhagman** [comment] 2015-08-20 19:34
The same thing is happening to me. +1

**Comment by alexmihai** [comment] 2015-09-22 07:22
+1

**Comment by tokudu** [comment] 2015-10-13 03:31
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/525

**Closed by tokudu** 2015-10-13 03:31 UTC
