### ISSUE TITLE
OnTouch event handling while menu is scrollable

### ISSUE THREAD

**Issue by changxiangzhong** [umano/AndroidSlidingUpPanel#489] opened 2015-07-06 11:25 UTC
Hi,

I want to express my appreciate of your work, this is really amazing project.

#### Issue description
I'm using a sliding-down menu(a menu located at the top of the screen) as the following screen indicates - the red area is the menu, the orange area is the main-body of the layout. The sliding menu contains a ListView. You can find two screen shots at the end.

##### Now the current situation is
1.  if a gesture is regarded as a fling, the SlidingUpPanelLayout would intercept the events **without** negotiating with child ListView
2. If a gesture is regarded as a scroll, the red ListView could receive the events in onTouchEvent.

##### My requirement is 
1. as long as the Red ListView is not having scrolled to the bottom, all the onTouch event should be handled by the red ListView. 
2. When the list is at the bottom, 
  * All the scrolling-up/fling-up gesture should be handled by the SlidingUpPanelLayout(because the listView is already at its bottom-most) 
  * Otherwise, the ListView handles. it.

##### Up menu collapsed:
![collapsed](https://cloud.githubusercontent.com/assets/5352145/8520979/c5d7510e-23df-11e5-8bae-17bc6ac23aaa.png)

##### Up menu expanded:
![expanded](https://cloud.githubusercontent.com/assets/5352145/8520981/c9cb36f4-23df-11e5-9291-34a629adda00.png)

Thank you in advance.

**Comment by changxiangzhong** [comment] 2015-07-06 12:18
Update:

I was wrong about the onFling & onScroll.

It is the ViewDragHelper::checkTouchSlop determines who to handle the onTouch event. When it's scrolled **very slow**, the **checkTouchSlop** method would regard it as a "touch slop" and will **NOT** intercept the event, so that the ListView will have the opportunity to scroll. When the scrolling is relatively fast, it will intercept the touch event.

**Comment by tokudu** [comment] 2015-07-08 06:44
Work in progress. Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/116

**Closed by tokudu** 2015-07-08 06:44 UTC
