### ISSUE TITLE
Slide up the bottom panel by sliding, with umanoPanelHeight = 0!

### ISSUE THREAD

**Issue by TroniPM** [umano/AndroidSlidingUpPanel#493] opened 2015-07-06 20:59 UTC
I want to slide up the bottom panel (in my case), by SLIDING UP, but i need to set umanoPanelHeight = 0 ("not showing"). Already made a button to expand the panel, but i need, even with this, to slide the bottom panel by touching (sliding the finger up)... Any ideas how to do something like that?

**Comment by tokudu** [comment] 2015-07-25 20:37
Not currently supported (dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/284). However, you can try to make the top of the panel transparent.

**Closed by tokudu** 2015-07-25 20:37 UTC
