### ISSUE TITLE
How to programmatically scroll 'SlidingLayout' by scrolling 'MainContaint' ?

### ISSUE THREAD

**Issue by AzimAnsari** [umano/AndroidSlidingUpPanel#537] opened 2015-09-10 11:09 UTC
![capture](https://cloud.githubusercontent.com/assets/10906758/9786795/79db6af4-57da-11e5-91a5-a6f0530f6870.PNG)

Currently I can scroll comment section to insert comments. I want to enable image scroll also to open comment section.

Whenever I scroll image up comment section should respond to scroll events.

I have added up/down scroll gestures to image but how can I pass these events to SlidingLayout?

**Comment by vsahu1986** [comment] 2015-09-21 11:46
+1

**Comment by vsahu1986** [comment] 2015-09-21 11:48
seems similar to 
#540

**Comment by vipinhelloindia** [comment] 2015-09-28 08:29
+1

**Comment by tokudu** [comment] 2015-10-13 03:39
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/529

**Closed by tokudu** 2015-10-13 03:39 UTC

**Comment by vipinhelloindia** [comment] 2015-10-30 04:52
Hi @tokudu  #537 is closed in 3.3.0  milestone ..
