### ISSUE TITLE
How to use scrollview include this panel

### ISSUE THREAD

**Issue by gaoshoubo** [umano/AndroidSlidingUpPanel#451] opened 2015-05-11 03:21 UTC
First tks to share this awesome project!
Then I need to use scrollview(the parent layout) include this panel,how can I solve it?tks

**Comment by tokudu** [comment] 2015-05-15 04:50
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/116

**Closed by tokudu** 2015-05-15 04:50 UTC
