### ISSUE TITLE
Disable touch input within dimmed area when using wrap_content as height

### ISSUE THREAD

**Issue by mpick92** [umano/AndroidSlidingUpPanel#438] opened 2015-04-19 23:20 UTC
I was surprised that touch input controlled the dimmed area (fragment view) behind my umano slider. My fix was to put an invisible button over the entire parent view and enabling it when the slider was expanded. I feel like this functionality could be a part of the AndroidSlidingUpPanel library. When this invisible button is clicked (the dimmed area), I collapse the umano slider.

**Comment by FireFly3000** [comment] 2015-07-06 13:27
I hope this only will be an option and wont be forced into the code as I am realy glad that it does exactly that.

**Comment by tokudu** [comment] 2016-02-02 07:05
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/476

**Closed by tokudu** 2016-02-02 07:05 UTC
Labels: FEATURE REQUEST
