### ISSUE TITLE
ListView inside SlidingUp Panel

### ISSUE THREAD

**Issue by devvenky0503** [umano/AndroidSlidingUpPanel#488] opened 2015-07-06 08:17 UTC
I added listview as the second view in the layout then the following issues are happening
1. Listview is taking up all the touch events.
2. When Panel is in full mode then event Listeners are arbitrarily chosen

**Comment by tokudu** [comment] 2015-07-08 06:44
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/116. Work in progress.

**Closed by tokudu** 2015-07-08 06:44 UTC
