### ISSUE TITLE
Main panel intercepts click events

### ISSUE THREAD

**Issue by NicolasLumb** [umano/AndroidSlidingUpPanel#385] opened 2015-02-12 16:21 UTC
Refering to #264 , I have the same problem.
I am using the SlidingUpPanel in a fragment and since the main layer is only used to create the shadow effect there is no need it to handle click events. However there is no way I can prevent this so the parent view cant get the touch events.
I have tried to extend and override the main class as is describe in #264, however some methods doesnt exist and some variables are declared private and cant be inherited.
Any guess how to solve this?
Thank you.

**Comment by tokudu** [comment] 2015-02-12 18:01
Marking a dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/264. Will be fixed in the next release.

**Closed by tokudu** 2015-02-12 18:01 UTC
