### ISSUE TITLE
Slide DragView With First Child 

### ISSUE THREAD

**Issue by vsahu1986** [umano/AndroidSlidingUpPanel#540] opened 2015-09-17 18:46 UTC
I have ScrollView as first child and Dragview as another Child . 
When I Scroll Scrollview , I wish the collapsed dragview should slide as parallax when reaches to end 

    public class ScrollViewEdge extends ScrollView {
    private ScrollViewListener scrollViewListener = null;
    SlidingUpPanelLayout slidingUpPanelLayout;
    boolean isEnabled;

    public ScrollViewEdge(Context context) {
        super(context);
    }

    public ScrollViewEdge(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    public ScrollViewEdge(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public void setScrollViewListener(ScrollViewListener scrollViewListener) {
        this.scrollViewListener = scrollViewListener;
    }

    @Override
    protected void onScrollChanged(int l, int t, int oldl, int oldt) {

        // Grab the last child placed in the ScrollView, we need it to determinate the bottom position.
        View view = (View) getChildAt(getChildCount() - 1);

        // Calculate the scrollDiff
        int diff = (view.getBottom() - (getHeight() + getScrollY()));

        // if diff is zero, then the bottom has been reached

        super.onScrollChanged(l, t, oldl, oldt);
        if (scrollViewListener != null) {
            scrollViewListener.onScrollChanged(this, t-oldt, t,diff);
        }
    }

    public void setSlider(SlidingUpPanelLayout slidingUpPanelLayout) {
        this.slidingUpPanelLayout = slidingUpPanelLayout;

    }

}    

     @TargetApi(14)
    public void onScrollChanged(ScrollViewEdge scrollView, int t_told, int scrollY, int scrollDiff) {
        int toolbarHeight =120;
        if(scrollDiff<90){
            float currentFooterTranslationY = ViewHelper.getTranslationY(dragView);
            if (firstScroll) {
                if (-toolbarHeight < currentFooterTranslationY) {
                    mBaseTranslationY = scrollY;
                    firstScroll=false;
                }
            }
            float headerTranslationY = UIUtils.getFloat(-(scrollY - mBaseTranslationY), -toolbarHeight, 0);
            ViewPropertyAnimator.animate(dragView).cancel();
            ViewHelper.setTranslationY(dragView, (int)headerTranslationY*1.2f);
        }

    }
    

This is what I managed to do , 
How can I slide the Dragview relative to ScrollView

**Comment by vsahu1986** [comment] 2015-09-23 12:10
if Managed to update height of Panel 

if (dragging) {
            if (firstScroll) {
                float currentHeaderTranslationY = mLayout.getPanelHeight();
                if (-toolbarHeight < currentHeaderTranslationY) {
                    mBaseTranslationY = scrollY;
                }
            }
            float headerTranslationY = ScrollUtils.getFloat(-(scrollY - mBaseTranslationY), -toolbarHeight, 0);
            Log.i("vipin","headerTranslationY" +headerTranslationY);
            mLayout.setPanelHeight(toolbarHeight-(int)headerTranslationY);
        }

but it call request layout , and is not the right way , 

Any update on this feature

**Comment by vsahu1986** [comment] 2015-09-28 08:16
Any update on this feature

**Comment by vipinhelloindia** [comment] 2015-09-28 09:19
+1

**Comment by tokudu** [comment] 2015-10-13 03:40
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/537

**Closed by tokudu** 2015-10-13 03:40 UTC
