### ISSUE TITLE
Close panel when touching the shadow

### ISSUE THREAD

**Issue by duduBaiao** [umano/AndroidSlidingUpPanel#519] opened 2015-08-06 04:53 UTC
Is it possible to close the panel when the user touches the shadow?

**Comment by dany-kun** [comment] 2015-08-06 16:16
One workaround could be to override dispatchTouchEvent in your activity/fragment view and check if the event is on the shadow or not

**Comment by duduBaiao** [comment] 2015-08-06 17:18
Thanks Dany!

To be honest, I was surprised that this is not the default behavior.

When we use an anchor point, is very intuitive try to touch at the shadow to close the panel.

For now, I removed the shadow. It seems that this way is less confusing.

**Comment by tokudu** [comment] 2016-02-02 07:08
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/476

**Comment by tokudu** [comment] 2016-02-06 03:36
FIxed in https://github.com/umano/AndroidSlidingUpPanel/commit/b69a6bf77e7c9e702815893f85b21703141701e2

Will be released in 3.3.0

**Closed by tokudu** 2016-02-06 03:36 UTC
Labels: FEATURE REQUEST
