### ISSUE TITLE
First call to setPanelState does not work

### ISSUE THREAD

**Issue by lupajz** [umano/AndroidSlidingUpPanel#393] opened 2015-02-20 20:45 UTC
I am building an app with AndroidSlidingUpPanel. I have an layout with listview as a main layout and linear layout with a some textviews as a sliding up layout. 

In the layout file I have set : 

     <com.sothree.slidinguppanel.SlidingUpPanelLayout
        android:id="@+id/sliding_up_panel_layout"
        xmlns:sup="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        sup:umanoPanelHeight="68dp"
        sup:umanoShadowHeight="2dp"
        sup:umanoFadeColor="@android:color/transparent"
        sup:umanoDragView="@+id/drag_view_header_text"
        sup:umanoInitialState="hidden"
        android:gravity="bottom">

Now on the launch of the app I have a piece of code wich will decide if the panel should stay hidden or should move to expanded state : 

    public void setupList(List<Restriction> list) {
        ...
       Log.e("Panel state before", String.valueOf(slidingUpPanelLayout.getPanelState()));
        if (adapter.getCount() == 0) {
            slidingUpPanelLayout.setPanelState(SlidingUpPanelLayout.PanelState.HIDDEN);
        } else {
            slidingUpPanelLayout.setPanelState(SlidingUpPanelLayout.PanelState.COLLAPSED);
        }
        Log.e("Panel state after", String.valueOf(slidingUpPanelLayout.getPanelState()));
    }

I would be expecting the panel to move to colapsed state, but it does not move there. The results from debugger : 
    E/Number of items﹕ 2
    E/Panel state before﹕ HIDDEN
    E/Panel state after﹕ HIDDEN

The problem is not there after I click different item from the main list. Then everything starts to work. 
Am I missing something ?

**Comment by tokudu** [comment] 2015-02-20 21:43
dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/386

**Closed by tokudu** 2015-02-20 21:43 UTC
