### ISSUE TITLE
Not work in target10

### ISSUE THREAD

**Issue by rahulwadhai** [umano/AndroidSlidingUpPanel#430] opened 2015-04-11 08:00 UTC
When i am use in target 2.3 its run but when touch on slide its crash 

04-11 10:55:20.910: E/AndroidRuntime(3225): FATAL EXCEPTION: main
04-11 10:55:20.910: E/AndroidRuntime(3225): java.lang.NoClassDefFoundError: com.nineoldandroids.view.animation.AnimatorProxy
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onPanelDragged(SlidingUpPanelLayout.java:974)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout.access$8(SlidingUpPanelLayout.java:964)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout$DragHelperCallback.onViewPositionChanged(SlidingUpPanelLayout.java:1204)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.sothree.slidinguppanel.ViewDragHelper.dragTo(ViewDragHelper.java:1393)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.sothree.slidinguppanel.ViewDragHelper.processTouchEvent(ViewDragHelper.java:1127)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onTouchEvent(SlidingUpPanelLayout.java:875)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.view.View.dispatchTouchEvent(View.java:3938)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:903)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1733)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1151)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2096)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1717)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2215)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.view.ViewRoot.handleMessage(ViewRoot.java:1886)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.os.Looper.loop(Looper.java:123)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at android.app.ActivityThread.main(ActivityThread.java:3687)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at java.lang.reflect.Method.invoke(Method.java:507)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
04-11 10:55:20.910: E/AndroidRuntime(3225): 	at dalvik.system.NativeStart.main(Native Method)
04-11 10:56:35.778: E/AndroidRuntime(3393): FATAL EXCEPTION: main
04-11 10:56:35.778: E/AndroidRuntime(3393): java.lang.NoClassDefFoundError: com.nineoldandroids.view.animation.AnimatorProxy
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onPanelDragged(SlidingUpPanelLayout.java:974)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout.access$8(SlidingUpPanelLayout.java:964)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout$DragHelperCallback.onViewPositionChanged(SlidingUpPanelLayout.java:1204)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.sothree.slidinguppanel.ViewDragHelper.dragTo(ViewDragHelper.java:1393)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.sothree.slidinguppanel.ViewDragHelper.processTouchEvent(ViewDragHelper.java:1127)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onTouchEvent(SlidingUpPanelLayout.java:875)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.view.View.dispatchTouchEvent(View.java:3938)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:903)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1733)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1151)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2096)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1717)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2215)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.view.ViewRoot.handleMessage(ViewRoot.java:1886)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.os.Looper.loop(Looper.java:123)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at android.app.ActivityThread.main(ActivityThread.java:3687)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at java.lang.reflect.Method.invoke(Method.java:507)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
04-11 10:56:35.778: E/AndroidRuntime(3393): 	at dalvik.system.NativeStart.main(Native Method)
04-11 10:57:17.100: E/AndroidRuntime(3443): FATAL EXCEPTION: main
04-11 10:57:17.100: E/AndroidRuntime(3443): java.lang.NoClassDefFoundError: com.nineoldandroids.view.animation.AnimatorProxy
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onPanelDragged(SlidingUpPanelLayout.java:974)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout.access$8(SlidingUpPanelLayout.java:964)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout$DragHelperCallback.onViewPositionChanged(SlidingUpPanelLayout.java:1204)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.sothree.slidinguppanel.ViewDragHelper.dragTo(ViewDragHelper.java:1393)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.sothree.slidinguppanel.ViewDragHelper.processTouchEvent(ViewDragHelper.java:1127)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onTouchEvent(SlidingUpPanelLayout.java:875)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.view.View.dispatchTouchEvent(View.java:3938)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:903)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1733)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1151)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2096)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1717)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2215)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.view.ViewRoot.handleMessage(ViewRoot.java:1886)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.os.Looper.loop(Looper.java:123)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at android.app.ActivityThread.main(ActivityThread.java:3687)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at java.lang.reflect.Method.invoke(Method.java:507)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
04-11 10:57:17.100: E/AndroidRuntime(3443): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by tokudu** [comment] 2015-04-12 00:33
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/432

**Closed by tokudu** 2015-04-12 00:33 UTC
