### ISSUE TITLE
Bug with Edittext

### ISSUE THREAD

**Issue by longnguyen0410** [umano/AndroidSlidingUpPanel#301] opened 2014-11-08 05:11 UTC
I have layout below:
"AndroidSlidingUpPane android:gravity="top" 
-------LinearLayout
-------------ListView
-------------EditText
-------LinearLayout
-------TextView
AndroidSlidingUpPanel"

Step 1: Slide down panel
Step 2: Slide up panel
Step 3: Touch on editext
Bug: Android keyboard show up but the keyboard overlay edittext, the edittext disapear :(

**Comment by tokudu** [comment] 2015-03-02 17:55
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/356

**Closed by tokudu** 2015-03-02 17:55 UTC
