### ISSUE TITLE
Compile failure in Android Studio 1.1

### ISSUE THREAD

**Issue by wangbourne** [umano/AndroidSlidingUpPanel#390] opened 2015-02-16 13:28 UTC
When trying to import, it comes an error of "Error:No such property: nexusUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer"

**Comment by tokudu** [comment] 2015-02-17 02:12
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/188

**Closed by tokudu** 2015-02-17 02:12 UTC
