### ISSUE TITLE
IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:1).state:7

### ISSUE THREAD

**Issue by kwmt** [umano/AndroidSlidingUpPanel#597] opened 2015-11-23 00:56 UTC
I'm using a RecyclerView as umanoScrollableView.  Sometimes IndexOutOfBundsException occur when probably  notifyDataSetChanged  is called.

I'm using version 3.1.1.
```
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:1).state:7
     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4401)
     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(SlidingUpPanelLayout.java:860)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
     at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
     at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2260)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2007)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
     at android.view.Choreographer.doCallbacks(Choreographer.java:591)
     at android.view.Choreographer.doFrame(Choreographer.java:561)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
     at android.os.Handler.handleCallback(HE/AndroidRuntime: FATAL EXCEPTION: main
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:1).state:7
     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4401)
     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(SlidingUpPanelLayout.java:860)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
     at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
     at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
     at android.view.View.layout(View.java:15204)
     at android.view.ViewGroup.layout(ViewGroup.java:4793)
     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2260)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2007)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
     at android.view.Choreographer.doCallbacks(Choreographer.java:591)
     at android.view.Choreographer.doFrame(Choreographer.java:561)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
     at android.os.Handler.handleCallback(Handler.java:730)
     at android.os.Handler.dispatchMessage(Handler.java:92)
     at android.os.Looper.loop(Looper.java:176)
     at android.app.ActivityThread.main(ActivityThread.java:5419)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:525)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
     at dalvik.system.NativeStart.main(Native Method)andler.java:730)
     at android.os.Handler.dispatchMessage(Handler.java:92)
     at android.os.Looper.loop(Looper.java:176)
     at android.app.ActivityThread.main(ActivityThread.java:5419)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:525)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by tokudu** [comment] 2015-11-24 07:47
Can you provide a sample project. I can't seem to reproduce this.

**Comment by dhpiggott** [comment] 2015-12-05 15:25
I'm getting a nearly identical exception. I've been using v3.2.0 along with the v23.0.1 support libraries, which work fine in combination. I get the exceptions when I (try to) switch to the v23.1.1 support libraries.

While trying to find similar reports just now, I came across https://code.google.com/p/android/issues/detail?id=77846.

@kwmt can you confirm which versions of the support libraries you are using, if any? And if you are currently using v23.1.1, it might be worth trying v23.0.1 and confirming whether you still have this issue then.

**Comment by tokudu** [comment] 2016-02-02 06:47
Closing this since it doesn't seem to be related to the library IMHO. Please reopen if you are still having issues.

**Closed by tokudu** 2016-02-02 06:47 UTC

**Comment by sagarkhakhar** [comment] 2016-02-02 09:49
This is encountered as bug in recycler view please refer given below links

https://code.google.com/p/android/issues/detail?can=1&q=77846&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&id=77846

https://code.google.com/p/android/issues/detail?id=77232

**Comment by ramt57** [comment] 2017-08-30 09:48
somtime it happen with ur item layout file .in my case i just remove margin from constraint layout in my case
