### ISSUE TITLE
[Question] Hard anchor point gone?

### ISSUE THREAD

**Issue by Siegbaert** [umano/AndroidSlidingUpPanel#534] opened 2015-08-31 13:26 UTC
Hey

I want to prevent the sliding panel to reach the EXPANDED state and just slide up to the ANCHORED state and not further.
By looking at the history I saw that there were already such requests and that there has been a solution by setting a hard anchor.
But in the current version it seems like this has been removed.
Is this still possible?
Or do i have to set the height of the panel programmatically?

**Comment by tokudu** [comment] 2015-10-13 03:37
It was never implemented. Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/125

**Closed by tokudu** 2015-10-13 03:37 UTC
