### ISSUE TITLE
setting panel state to hidden doesn't work

### ISSUE THREAD

**Issue by rajatpandit** [umano/AndroidSlidingUpPanel#386] opened 2015-02-13 23:05 UTC
i am using the slideupanel in the context of a drawer menu, an older version of the code worked fine but compiling this in api 21 doesn't work. unfortunately i dont' know the version of the working instance as in my gradle config, i had used a wild card.

has anyone else had this problem?

java code
```
        if (slidingUpPanelLayout.getPanelState() != PanelState.HIDDEN) {
            slidingUpPanelLayout.setPanelState(PanelState.HIDDEN);
        }
```

layout xml
```
 <!-- A DrawerLayout is intended to be used as the top-level content view using match_parent for both width and height to consume the full space available. -->
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".MainActivity">


    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.sothree.slidinguppanel.SlidingUpPanelLayout
            xmlns:sothree="http://schemas.android.com/apk/com.vc.audiocontent"
            android:id="@+id/player_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="bottom"
            sothree:fadeColor="@android:color/darker_gray"
            sothree:overlay="true"
            sothree:umanoPanelHeight="68dp"
            sothree:umanoParalaxOffset="100dp"
            sothree:umanoShadowHeight="4dp">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:clickable="true"
                android:focusable="false"
                android:orientation="vertical">

                <android.support.v7.widget.Toolbar
                    android:id="@+id/main_toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="?attr/colorPrimary"
                    android:minHeight="?attr/actionBarSize" />

                <FrameLayout
                    android:id="@+id/container"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />


            </LinearLayout>


            <fragment
                android:id="@+id/player"
                android:name="com.vc.audiocontent.PlayerFragment"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                tools:layout="@layout/fragment_player" />

        </com.sothree.slidinguppanel.SlidingUpPanelLayout>

    </LinearLayout>


    <!-- android:layout_gravity="start" tells DrawerLayout to treat
         this as a sliding drawer on the left side for left-to-right
         languages and on the right side for right-to-left languages.
         If you're not building against API 17 or higher, use
         android:layout_gravity="left" instead. -->
    <!-- The drawer is given a fixed width in dp and extends the full height of
         the container. -->

    <fragment
        android:id="@+id/playlist_drawer"
        android:name="com.vc.audiocontent.PlaylistFragment"
        android:layout_width="@dimen/navigation_playlist_width"
        android:layout_height="match_parent"
        android:layout_gravity="end"
        tools:layout="@layout/fragment_playlist" />

    <fragment
        android:id="@+id/navigation_drawer"
        android:name="com.vc.audiocontent.NavigationDrawerFragment"
        android:layout_width="@dimen/navigation_drawer_width"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        tools:layout="@layout/fragment_navigation_drawer" />

</android.support.v4.widget.DrawerLayout>

```

**Comment by rajatpandit** [comment] 2015-02-14 15:34
downgraded to 2.0.4 and it has started to work again now.

**Comment by polson** [comment] 2015-02-15 23:11
I'm also seeing this issue on 3.0.0.  

I worked around it by setting the height to 0:
```
panel.setPanelHeight(0);
```

And then restoring it when I want to show the panel:
```
panel.setPanelHeight(getResources().getDimensionPixelSize(R.dimen.panel_height));
```

**Comment by mathieudebrito** [comment] 2015-02-16 16:05
+1

**Comment by miskooooo** [comment] 2015-02-19 00:19
Hello,
I have same problem and  height(0) is not good solution for me.

**Comment by tokudu** [comment] 2015-02-19 16:39
Thank you for the report guys. I will look into this for the next point release

**Comment by tokudu** [comment] 2015-03-02 17:35
I fixed one issue related to not being able to set the state before the first layout is called (https://github.com/umano/AndroidSlidingUpPanel/commit/468bb12b361348b3a67112445da2f0d8652a8b7d). However, I can't reproduce the issue otherwise. As you can see the demo project does exactly what you are trying to do: 

```
                    if (mLayout.getPanelState() != PanelState.HIDDEN) {
                        mLayout.setPanelState(PanelState.HIDDEN);
                        item.setTitle(R.string.action_show);
                    }
```

Please try the version of master or let me know how I can reproduce in the demo project.

**Closed by tokudu** 2015-03-02 17:35 UTC
