### ISSUE TITLE
Add support for RecycleView in umanoScrollableView

### ISSUE THREAD

**Issue by marinica94** [umano/AndroidSlidingUpPanel#485] opened 2015-06-30 18:46 UTC
Is there a way how to fix functionality of my RecyclerView after implementing SlidingUpPanel ?

**Comment by tokudu** [comment] 2015-07-18 22:11
Not sure what you mean - can you describe in more detail the issue that you are facing.

**Comment by pdavid0** [comment] 2015-07-21 18:24
I'm not speaking for OP, but I too have tremendous amount of problems with recyclerview.

When I try to scroll the view either to recyclerview doesn't scroll or the pane starts collapsing instead of letting me get back to the top of the recyclerview content.

I tried with umanoScrollView but is seems it only supports ListView for now.
I tried a lot of weird stuff like : disabling the scrolling on the recycler, disabling the sliding pane ..

Do you have a working example with RecyclerView ?

Thanks for the support, great lib :+1:

**Comment by tokudu** [comment] 2015-07-21 18:43
Only ListView and ScrollView are currently supported as scrollable children. I will add support for the RecyclerView in the next release.

**Comment by pdavid0** [comment] 2015-07-21 18:44
any ETA ?

**Comment by tokudu** [comment] 2015-07-21 18:53
Not sure. However, the support should be fairly easy to add. You just need to modify `getScrollableViewScrollPosition`, which returns the current scroll position of the view based on the class.
https://github.com/umano/AndroidSlidingUpPanel/blob/master/library/src/com/sothree/slidinguppanel/SlidingUpPanelLayout.java#L1014

Feel free to send me a PR if you get to it before I do

**Comment by pdavid0** [comment] 2015-07-22 03:13
Done PR: https://github.com/umano/AndroidSlidingUpPanel/pull/507

**Comment by pdavid0** [comment] 2015-07-26 22:00
Redid the PR with what you asked. PR : https://github.com/umano/AndroidSlidingUpPanel/pull/514

**Comment by tokudu** [comment] 2015-07-26 22:55
Fixed in master. Will be released in 3.1.2

**Comment by Sottti** [comment] 2015-08-24 15:58
Really looking forward this one to be released. Any ETA on 3.1.2?? Thanks a lot for the great lib.

**Comment by papageorgiouk** [comment] 2015-08-25 10:05
You mean you can't scroll the RecyclerView because the Sliding Panel intercepts all touch events, right? You can set a draggable area with 'sothree:umanoDragView="@+id/..."', outside of which the panel doesn't intercept touch events.

In the XML layout:

    <com.sothree.slidinguppanel.SlidingUpPanelLayout
        ...
        ...
        ...
        sothree:umanoDragView="@+id/..."

    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

Or you can set it programmatically:
```
slidingUpPanelLayout.setDragView(findViewById(R.id....))
```

**Comment by Sottti** [comment] 2015-08-25 12:33
Yes, I've done that. What I'd like to do (I've tried but it's not working okay) is changing the dragView depending on the scroll position like Google Maps is working at the moment.

Let's say for example that my sliding panel is on the bottom of the screen and slides up. The panel is a header and a recycler view. Clicking on the header opens/closes the panel, but I'd like as well that when the scroll is all the way up (findfirstcompletelyvisibleitemposition == 0) the whole panel acts like the dragView.

I've tried to achieve this but I couldn't get it. The problem is that which element is intercepting the events (recycler view vs sliding panel) looks random.

**Comment by renannery** [comment] 2015-08-30 22:07
Any ETA for 3.1.2?

**Comment by dellby** [comment] 2015-08-31 12:17
Hello.
I am using GoogleMap (dragView in bottom: 
TextView 
RecyclerView).

1. sliding up works well, 
2. but down - no (TextView overlapRecyclerView ) the list does not refresh
ver 3.1.1

**Comment by xiaolongyuan** [comment] 2015-09-25 02:33
Any ETA for 3.1.2? +1

**Comment by marinica94** [comment] 2015-09-27 13:39
^1 +1

**Comment by AlexQuinlivan** [comment] 2015-09-28 03:45
+1 to a release with this included. Would be great if PR #543 could also get rolled into 3.1.2

**Comment by marinica94** [comment] 2015-09-30 08:06
What I've seen today: Philippe David on Jul 27 add recyclerview support on https://github.com/umano/AndroidSlidingUpPanel/blob/master/library/src/com/sothree/slidinguppanel/SlidingUpPanelLayout.java#L1014 and what I've seen in code it now have recyclerView support, just use the 3.1.1 version and will work, going to test it today.

**Comment by githubdoramon** [comment] 2015-10-02 01:54
Using the version 3.1.1 and is not working with the recycler view... Any news on the release?

**Comment by marinica94** [comment] 2015-10-02 05:03
I ve succesfully implemented the library in my recyclerview and works like a charm

**Comment by pdavid0** [comment] 2015-10-02 13:49
While waiting for the "official release" you can just copy/paste the classes/modifs in your project.

**Comment by WarrenFaith** [comment] 2015-10-06 21:15
Easier is the solution from @papageorgiouk at his comment: https://github.com/umano/AndroidSlidingUpPanel/issues/485#issuecomment-134544995

I just set the toolbar as a dragview and it works like charme

**Comment by tokudu** [comment] 2015-10-06 22:22
I'll release it this weekend.

Anton

**Comment by tokudu** [comment] 2015-10-13 03:51
Released.

**Closed by tokudu** 2015-10-13 03:51 UTC
Labels: FEATURE REQUEST

**Comment by Sottti** [comment] 2015-10-14 13:29
Works like a charm, thanks, that's great.

**Comment by coRz** [comment] 2015-11-09 13:02
Guys I still got that issue, I have SlidingUpPanelLayout with ViewPager (having 3 fragments inside with different lists (RecyclerViews). It is not scrolling the inner lists only drags the panel to the top, only when I hold my finger for a second on the list it starts receiving the touch events.

**Comment by stoichoandreev** [comment] 2015-12-15 12:31
Hi there,
I am having the same issue, with 3.2.0. In my xml I have recycler view with horizontal scroll inside the panel. The problem that I have is : I don’t want this recycler view to pass drag or click event to the panel,  I just need horizontal scroll on it, and it should consume all touch event and not passing them to the panel. It is working fine in all possible cases instate in the case when data into recycler view is in the beginning and I am scrolling. Some of the touch events are passed to the panel and it try to collapse. When scroll has a little progress my recycler view is working like I want, only horizontal scroll but not the vertical drag for the panel.
I have this setting in xml customs:umanoScrollableView="@+id/playback_start_screen_recycler_view”

and also my recycler view has android:clickable="true"

Is there anything that I am missing?
Here is just part of my layout file:
<com.sothree.slidinguppanel.SlidingUpPanelLayout
        android:id="@+id/sliding_panel_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom"
        customs:umanoShadowHeight="4dp"
        customs:umanoDragView="@+id/playback_start_screen_slide_panel_layout"
        customs:umanoScrollableView="@+id/playback_start_screen_recycler_view"
        customs:umanoPanelHeight="@dimen/playback_start_screen_tab_little_open_height">

**Comment by Hemant0601** [comment] 2016-03-03 09:12
I am using 3.2.1 but still facing the same issue of recycler view not scrollable. Please help

**Comment by rkoshti** [comment] 2023-07-04 06:47
any update on this ?
