### ISSUE TITLE
How to change the velocity of Panel

### ISSUE THREAD

**Issue by 12520054** [umano/AndroidSlidingUpPanel#495] opened 2015-07-09 11:02 UTC
Hi there,
I don't know how to change or reduce the flyingvelocity of Panel.
When it Hidden and I change State to Expand or when it Expand I change to Hidden. It's move to fast.
I have change the         sothree:umanoFlingVelocity="50" but It make no slowly effect.
Thanks for any help.

**Comment by Bierrot** [comment] 2015-07-13 07:31
Same here

**Comment by tokudu** [comment] 2015-07-18 21:38
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/365

**Closed by tokudu** 2015-07-18 21:38 UTC

**Comment by abhiank209** [comment] 2016-02-15 11:24
@tokudu Has this feature been implemented yet?
